name: eksaminiaia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  get: ^4.6.5
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.1
  logger: ^1.4.0
  firebase_storage: ^12.3.7
  image_picker: ^0.8.7
  just_audio: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/button_image.png
   - assets/images/house.png
   - assets/images/firstplace.png
   - assets/images/secondplace.png
   - assets/images/thridplace.png
   - assets/images/ready_arrow.png
   - assets/images/boom.png
   - assets/images/done.png
   - assets/images/stop.png
   - assets/images/hourglass.png
   - assets/images/start.png
   - assets/images/chat.png
