// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlV6tIb7_XQGW7xyQzfvrbUdkPWwAa20s',
    appId: '1:958732696217:web:d03e5c840527a6eb7c9608',
    messagingSenderId: '958732696217',
    projectId: 'eksaminiaia-8c996',
    authDomain: 'eksaminiaia-8c996.firebaseapp.com',
    databaseURL: 'https://eksaminiaia-8c996-default-rtdb.firebaseio.com',
    storageBucket: 'eksaminiaia-8c996.firebasestorage.app',
    measurementId: 'G-VGZJ7009JR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVg37Rjk3dL1nwegv_eZ6fmMx5FARe1gU',
    appId: '1:958732696217:android:72792831dc95bf447c9608',
    messagingSenderId: '958732696217',
    projectId: 'eksaminiaia-8c996',
    databaseURL: 'https://eksaminiaia-8c996-default-rtdb.firebaseio.com',
    storageBucket: 'eksaminiaia-8c996.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAE5zQJXb71ygrkWKWfcGMIP8NfNhGsBoQ',
    appId: '1:958732696217:ios:d01fa4036a2fdeb97c9608',
    messagingSenderId: '958732696217',
    projectId: 'eksaminiaia-8c996',
    databaseURL: 'https://eksaminiaia-8c996-default-rtdb.firebaseio.com',
    storageBucket: 'eksaminiaia-8c996.firebasestorage.app',
    iosBundleId: 'com.example.eksaminiaia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAE5zQJXb71ygrkWKWfcGMIP8NfNhGsBoQ',
    appId: '1:958732696217:ios:d01fa4036a2fdeb97c9608',
    messagingSenderId: '958732696217',
    projectId: 'eksaminiaia-8c996',
    databaseURL: 'https://eksaminiaia-8c996-default-rtdb.firebaseio.com',
    storageBucket: 'eksaminiaia-8c996.firebasestorage.app',
    iosBundleId: 'com.example.eksaminiaia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlV6tIb7_XQGW7xyQzfvrbUdkPWwAa20s',
    appId: '1:958732696217:web:1f4e37daf966f0cf7c9608',
    messagingSenderId: '958732696217',
    projectId: 'eksaminiaia-8c996',
    authDomain: 'eksaminiaia-8c996.firebaseapp.com',
    databaseURL: 'https://eksaminiaia-8c996-default-rtdb.firebaseio.com',
    storageBucket: 'eksaminiaia-8c996.firebasestorage.app',
    measurementId: 'G-0W8HXYK7EG',
  );

}