import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:get/get.dart';
import 'pages/join.dart'; 
import 'firebase_options.dart'; // Generated by the Firebase CLI
// Import the RoomInputPage




void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: 'Room Manager',
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const RoomInputPage(),
    );
  }
}
